sudo: required  # sudo permission
services:       # tells travis-ci to use docker
  - docker

before_install:   # run command to build docker container
  - docker build -t Aleemsl90/docker-react -f Dockerfile.dev .

script:       # run test and display result
  - docker run Aleemsl90/docker-react npm run test -- --coverage

deploy:       # tells travis-CI to deploy to AWS
  provider: elasticbeanstalk    # scalable AWS env (loadbalancer + VM running docker) adds extra VMs when one is full
  region: "us-west-2"       # region while setting up elasticbeanstalk
  app: "docker-react"       # app name given while setting up elasticbeanstalk
  env: "Docker-env"         # auto name of environment
  bucket_name: "elasticbeanstalk-us-west-2-{s3bucketID}"  # search s3 bucket for your env and copy ID
  bucket_path: "docker-react"   # default app name
  on:     # tells travis-CI when we master branch gets new code
    branch: master
  access_key_id: $AWS_ACCESS_KEY  # Name of env variable in travis-ci
  secret_access_key: $AWS_SECRET_KEY  # Name of env variable in travis-ci